/* Ridgeline MES — master data: plant layout, personnel, parts, BOMs, routings and baseline quality plans. */
'use strict';

const MASTER = (() => {
  const company = { name: 'Ridgeline Motor Works', plant: 'Plant 1 · Fort Wayne', product: 'Trailhand T1' };

  const buildings = [
    { id: 'B10', name: 'Building 10 — Body Shop', short: 'Body Shop' },
    { id: 'B20', name: 'Building 20 — Powertrain', short: 'Powertrain' },
    { id: 'B30', name: 'Building 30 — Final Assembly', short: 'Final Assembly' },
    { id: 'B40', name: 'Building 40 — Logistics Center', short: 'Logistics' },
  ];

  const locations = [
    { id: 'B40-RCV', name: 'Receiving Dock 3', building: 'B40', type: 'Receiving' },
    { id: 'B40-A01', name: 'High-bay Rack A01', building: 'B40', type: 'Storage' },
    { id: 'B40-A02', name: 'High-bay Rack A02', building: 'B40', type: 'Storage' },
    { id: 'B40-QRT', name: 'Quarantine Cage', building: 'B40', type: 'Quarantine' },
    { id: 'B10-LS', name: 'Body Line-side Supermarket', building: 'B10', type: 'Line-side' },
    { id: 'B10-FG', name: 'Body Buffer (painted bodies)', building: 'B10', type: 'Finished' },
    { id: 'B20-LS', name: 'Powertrain Line-side Supermarket', building: 'B20', type: 'Line-side' },
    { id: 'B20-FG', name: 'Engine Dispatch Dock', building: 'B20', type: 'Finished' },
    { id: 'B30-LS', name: 'Final Assembly Line-side / Sequencing', building: 'B30', type: 'Line-side' },
    { id: 'B30-FG', name: 'Ship Yard Lane 2', building: 'B30', type: 'Finished' },
    { id: 'B30-MRB', name: 'MRB Cage (Quality)', building: 'B30', type: 'Quarantine' },
  ];

  const stations = [
    { id: 'B10-UB1', name: 'Underbody Framing Cell', building: 'B10', wc: 'Body Framing' },
    { id: 'B10-SF1', name: 'Side Frame Weld Cell', building: 'B10', wc: 'Body Framing' },
    { id: 'B10-CL1', name: 'Closures Hang Line', building: 'B10', wc: 'Closures' },
    { id: 'B10-CMM', name: 'CMM Dimensional Room', building: 'B10', wc: 'Body Quality' },
    { id: 'B10-PNT', name: 'E-coat & Paint Booth 2', building: 'B10', wc: 'Paint' },
    { id: 'B10-BFI', name: 'Body Final Inspection', building: 'B10', wc: 'Body Quality' },
    { id: 'B20-BLK', name: 'Block Prep & Serialization', building: 'B20', wc: 'Short Block' },
    { id: 'B20-CRK', name: 'Crank & Piston Install', building: 'B20', wc: 'Short Block' },
    { id: 'B20-HD', name: 'Head & Valvetrain', building: 'B20', wc: 'Long Block' },
    { id: 'B20-DRS', name: 'Turbo & ECU Dress', building: 'B20', wc: 'Engine Dress' },
    { id: 'B20-CT', name: 'Cold Test Cell CT-1', building: 'B20', wc: 'Engine Test' },
    { id: 'B20-HT', name: 'Hot Test Cell HT-2', building: 'B20', wc: 'Engine Test' },
    { id: 'B30-TR1', name: 'Body Marriage & VIN', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-TR2', name: 'Main Harness Routing', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-TR3', name: 'Headliner & Roof Trim', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-TR4', name: 'Instrument Panel Install', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-TR5', name: 'Instrument Cluster', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-TR6', name: 'Center Console & Shifter', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-TR7', name: 'Infotainment Head Unit', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-TR8', name: 'Steering Column & Wheel', building: 'B30', wc: 'Trim 1' },
    { id: 'B30-DK', name: 'Powertrain Decking', building: 'B30', wc: 'Chassis' },
    { id: 'B30-CH1', name: 'Front Suspension & Steering Rack', building: 'B30', wc: 'Chassis' },
    { id: 'B30-CH2', name: 'Rear Axle & Suspension', building: 'B30', wc: 'Chassis' },
    { id: 'B30-CH3', name: 'Brake & Fuel Lines', building: 'B30', wc: 'Chassis' },
    { id: 'B30-CH4', name: 'Exhaust & Heat Shields', building: 'B30', wc: 'Chassis' },
    { id: 'B30-CH5', name: 'Wheels & Tires', building: 'B30', wc: 'Chassis' },
    { id: 'B30-TG1', name: 'Glass Install', building: 'B30', wc: 'Trim 2' },
    { id: 'B30-TG2', name: 'Doors & Door Trim', building: 'B30', wc: 'Trim 2' },
    { id: 'B30-TG3', name: 'Front Seats', building: 'B30', wc: 'Trim 2' },
    { id: 'B30-TG4', name: 'Rear Seat', building: 'B30', wc: 'Trim 2' },
    { id: 'B30-TG5', name: 'Restraints & SRS', building: 'B30', wc: 'Trim 2' },
    { id: 'B30-TG6', name: 'Exterior Lighting & Indicators', building: 'B30', wc: 'Trim 2' },
    { id: 'B30-TG7', name: 'Bumpers, Grille & Mirrors', building: 'B30', wc: 'Trim 2' },
    { id: 'B30-FL1', name: 'Fluids Fill', building: 'B30', wc: 'Final' },
    { id: 'B30-FL2', name: 'Battery & 12V Electrical', building: 'B30', wc: 'Final' },
    { id: 'B30-FL3', name: 'Module Flash & Configuration', building: 'B30', wc: 'Final' },
    { id: 'B30-EOL1', name: 'Alignment & Headlamp Aim', building: 'B30', wc: 'Vehicle Test' },
    { id: 'B30-EOL2', name: 'Roll & Brake Test', building: 'B30', wc: 'Vehicle Test' },
    { id: 'B30-EOL3', name: 'ADAS Calibration', building: 'B30', wc: 'Vehicle Test' },
    { id: 'B30-WT', name: 'Water Test Booth', building: 'B30', wc: 'Vehicle Test' },
    { id: 'B30-AUD', name: 'Final Audit & Ship Release', building: 'B30', wc: 'Vehicle Test' },
  ];

  const S = id => id;
  const people = [
    { id: 'U101', name: 'Maria Delgado', role: 'Operator', badge: '40117', shift: 'A', building: 'B10', quals: ['B10-UB1', 'B10-SF1', 'B10-CL1'] },
    { id: 'U102', name: 'Jamal Pierce', role: 'Operator', badge: '40152', shift: 'A', building: 'B10', quals: ['B10-CL1', 'B10-PNT', 'B10-BFI', 'B10-SF1'] },
    { id: 'U103', name: 'Tran Nguyen', role: 'Operator', badge: '40233', shift: 'A', building: 'B20', quals: ['B20-BLK', 'B20-CRK', 'B20-HD'] },
    { id: 'U104', name: 'Olivia Hart', role: 'Operator', badge: '40261', shift: 'A', building: 'B20', quals: ['B20-HD', 'B20-DRS', 'B20-CT', 'B20-HT'] },
    { id: 'U105', name: 'Ken Watanabe', role: 'Operator', badge: '40288', shift: 'B', building: 'B20', quals: ['B20-BLK', 'B20-CRK', 'B20-DRS', 'B20-CT', 'B20-HT'] },
    { id: 'U106', name: 'Dmitri Volkov', role: 'Operator', badge: '40314', shift: 'A', building: 'B30', quals: ['B30-TR1', 'B30-TR2', 'B30-TR3', 'B30-TR4', 'B30-TR5', 'B30-TR6', 'B30-TR7', 'B30-TR8'] },
    { id: 'U107', name: 'Aisha Rahman', role: 'Operator', badge: '40339', shift: 'A', building: 'B30', quals: ['B30-TR5', 'B30-TR6', 'B30-TR7', 'B30-TR8', 'B30-TG1', 'B30-TG2', 'B30-TG3', 'B30-TG4'] },
    { id: 'U108', name: 'Carlos Mendes', role: 'Operator', badge: '40372', shift: 'A', building: 'B30', quals: ['B30-EOL1', 'B30-EOL2', 'B30-EOL3', 'B30-WT', 'B30-AUD', 'B30-FL1', 'B30-FL2', 'B30-FL3'] },
    { id: 'U109', name: 'Grace Kim', role: 'Operator', badge: '40391', shift: 'A', building: 'B30', quals: ['B30-DK', 'B30-CH1', 'B30-CH2', 'B30-CH3', 'B30-CH4', 'B30-CH5'] },
    { id: 'U110', name: 'Luis Ortega', role: 'Operator', badge: '40407', shift: 'A', building: 'B30', quals: ['B30-TG1', 'B30-TG2', 'B30-TG3', 'B30-TG4', 'B30-TG5', 'B30-TG6', 'B30-TG7'] },
    { id: 'U111', name: 'Hannah Weiss', role: 'Operator', badge: '40416', shift: 'B', building: 'B30', quals: ['B30-FL1', 'B30-FL2', 'B30-FL3', 'B30-TG5', 'B30-TG6', 'B30-TG7'] },
    { id: 'U112', name: 'Omar Haddad', role: 'Operator', badge: '40428', shift: 'B', building: 'B30', quals: ['B30-DK', 'B30-CH1', 'B30-CH2', 'B30-CH3', 'B30-CH4', 'B30-CH5', 'B30-TR1', 'B30-TR2'] },
    { id: 'U201', name: 'Rosa Jimenez', role: 'Material Handler', badge: '51004', shift: 'A', building: 'B40', quals: [] },
    { id: 'U202', name: 'Tom Becker', role: 'Material Handler', badge: '51019', shift: 'B', building: 'B40', quals: [] },
    { id: 'U301', name: 'Sam Ortiz', role: 'Quality Technician', badge: '62010', shift: 'A', building: 'B10', quals: ['B10-CMM', 'B10-BFI', 'B20-CT', 'B20-HT', 'B30-EOL1', 'B30-EOL2', 'B30-EOL3', 'B30-WT', 'B30-AUD'] },
    { id: 'U302', name: 'Priya Shah', role: 'Quality Engineer', badge: '62045', shift: 'A', building: 'B30', quals: [] },
    { id: 'U303', name: 'Daniel Okafor', role: 'Quality Engineer', badge: '62071', shift: 'A', building: 'B20', quals: [] },
    { id: 'U401', name: 'Linda Park', role: 'Supervisor', badge: '70003', shift: 'A', building: 'B30', quals: ['B30-TR1', 'B30-TR2', 'B30-TR3', 'B30-TR4', 'B30-TR5', 'B30-TR6', 'B30-TR7', 'B30-TR8', 'B30-DK', 'B30-CH1', 'B30-CH2', 'B30-CH3', 'B30-CH4', 'B30-CH5', 'B30-TG1', 'B30-TG2', 'B30-TG3', 'B30-TG4', 'B30-TG5', 'B30-TG6', 'B30-TG7', 'B30-FL1', 'B30-FL2', 'B30-FL3', 'B30-EOL1', 'B30-EOL2', 'B30-EOL3', 'B30-WT', 'B30-AUD'] },
    { id: 'U402', name: 'Marcus Reed', role: 'Supervisor', badge: '70011', shift: 'A', building: 'B20', quals: ['B10-UB1', 'B10-SF1', 'B10-CL1', 'B10-CMM', 'B10-PNT', 'B10-BFI', 'B20-BLK', 'B20-CRK', 'B20-HD', 'B20-DRS', 'B20-CT', 'B20-HT'] },
  ];
  people.forEach(p => { p.pin = '1234'; p.active = true; });

  /* tracking: Serial | Lot | None. pattern = regex the scanned serial must match. */
  const parts = [
    // assemblies (manufactured)
    { id: 'BIW-T1', name: 'Body-in-White, Crew Cab (painted)', uom: 'EA', type: 'Assembly', tracking: 'Serial', pattern: '^BT1-\\d{6}-\\d{4}$', building: 'B10' },
    { id: 'ENG-24T', name: 'Engine Assy 2.4L I4 Turbo', uom: 'EA', type: 'Assembly', tracking: 'Serial', pattern: '^E24T-\\d{6}-\\d{4}$', building: 'B20' },
    { id: 'VEH-T1', name: 'Trailhand T1 Pickup, Crew Cab 4x4', uom: 'EA', type: 'Assembly', tracking: 'Serial', pattern: 'VIN', building: 'B30' },
    // body
    { id: 'UB-1001', name: 'Underbody Pan Assy', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Stamping Co.' },
    { id: 'SF-2001L', name: 'Side Frame Outer, LH', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Stamping Co.' },
    { id: 'SF-2001R', name: 'Side Frame Outer, RH', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Stamping Co.' },
    { id: 'RF-3001', name: 'Roof Panel', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Stamping Co.' },
    { id: 'HD-3101', name: 'Hood Assy', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Lakeshore Closures' },
    { id: 'DR-3201', name: 'Door Assy, Front (LH/RH)', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Lakeshore Closures' },
    { id: 'TG-3301', name: 'Tailgate Assy', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Lakeshore Closures' },
    { id: 'SEA-9001', name: 'Structural Sealer, 2K Epoxy', uom: 'L', type: 'Purchased', tracking: 'Lot', supplier: 'Adhera Chemicals' },
    { id: 'PNT-9002', name: 'Topcoat, Glacier White', uom: 'L', type: 'Purchased', tracking: 'Lot', supplier: 'Adhera Chemicals' },
    // engine
    { id: 'EB-4001', name: 'Engine Block, Aluminum 2.4L', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^EB\\d{8}$', supplier: 'Great Lakes Castings' },
    { id: 'CK-4101', name: 'Crankshaft, Forged', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^CK-[A-Z]\\d{6}$', supplier: 'Keystone Forge' },
    { id: 'PS-4201', name: 'Piston Assy w/ Rings', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Precision Piston Inc.' },
    { id: 'CR-4202', name: 'Connecting Rod, Cracked Cap', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Keystone Forge' },
    { id: 'CH-4301', name: 'Cylinder Head, DOHC', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^CH\\d{7}$', supplier: 'Great Lakes Castings' },
    { id: 'CS-4302', name: 'Camshaft (Intake/Exhaust)', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Keystone Forge' },
    { id: 'TC-4401', name: 'Turbocharger, Twin-scroll', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^TT4\\d{7}$', supplier: 'Borealis Turbo' },
    { id: 'EC-4501', name: 'Engine Control Module', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^ECU-[0-9A-F]{8}$', supplier: 'Vantec Electronics' },
    { id: 'GK-4601', name: 'Gasket & Seal Kit', uom: 'KIT', type: 'Purchased', tracking: 'Lot', supplier: 'SealRite' },
    { id: 'OL-9101', name: 'Engine Oil 5W-30 Full Synthetic', uom: 'L', type: 'Purchased', tracking: 'Lot', supplier: 'Petrolux' },
    // vehicle
    { id: 'TR-5001', name: 'Transmission, 8-speed Automatic', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^TX8A\\d{6}$', supplier: 'Allied Drivetrain' },
    { id: 'AX-5101', name: 'Rear Axle Assy, 3.73 e-Locker', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^AX\\d{7}$', supplier: 'Allied Drivetrain' },
    { id: 'WT-5201', name: 'Wheel & Tire Assy 265/70R17', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Summit Wheel & Tire' },
    { id: 'AB-6001', name: 'Airbag Module, Driver', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^DAB\\d{8}$', supplier: 'Safeguard Restraints' },
    { id: 'AB-6002', name: 'Airbag Module, Passenger', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^PAB\\d{8}$', supplier: 'Safeguard Restraints' },
    { id: 'SB-6101', name: 'Seat Belt Pretensioner, Front', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^PT\\d{8}$', supplier: 'Safeguard Restraints' },
    { id: 'BT-7001', name: 'Battery, 12V AGM H6', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^BAT\\d{7}$', supplier: 'Voltline' },
    { id: 'WH-7101', name: 'Main Wiring Harness', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Vantec Electronics' },
    { id: 'IP-8001', name: 'Instrument Panel Module w/ Cross-car Beam', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Cockpit Systems NA' },
    { id: 'IC-8101', name: 'Instrument Cluster, 12.3in Digital', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^IC\\d{8}$', supplier: 'Vantec Electronics' },
    { id: 'CN-8151', name: 'Center Console Assy w/ Armrest', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Cockpit Systems NA' },
    { id: 'SH-8161', name: 'Electronic Shifter Module', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Allied Drivetrain' },
    { id: 'HU-8201', name: 'Infotainment Head Unit, 12in', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^HU\\d{8}$', supplier: 'Vantec Electronics' },
    { id: 'SC-8301', name: 'Steering Column, Electric Power Assist', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^SC\\d{8}$', supplier: 'Keystone Steering' },
    { id: 'SW-8311', name: 'Steering Wheel, Heated Leather', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Keystone Steering' },
    { id: 'HL-8021', name: 'Headliner Assy', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Interior Trim Co.' },
    { id: 'RK-5301', name: 'Steering Rack, EPS', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Keystone Steering' },
    { id: 'FL-5401', name: 'Fuel Line Kit', uom: 'KIT', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Tube' },
    { id: 'EX-5501', name: 'Exhaust System Assy', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Tube' },
    { id: 'WS-8501', name: 'Windshield, Acoustic w/ Camera Bracket', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Clearview Glass' },
    { id: 'UR-9301', name: 'Urethane Glass Adhesive', uom: 'L', type: 'Purchased', tracking: 'Lot', supplier: 'Adhera Chemicals' },
    { id: 'DT-8551', name: 'Door Trim Panel (LH/RH)', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Interior Trim Co.' },
    { id: 'SE-8401', name: 'Front Seat Assy w/ Occupant Sensor', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^SE\\d{8}$', supplier: 'Contour Seating' },
    { id: 'RS-8451', name: 'Rear Bench Seat 60/40', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Contour Seating' },
    { id: 'LP-8601', name: 'Headlamp, LED Matrix', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Lumen Automotive' },
    { id: 'TI-8611', name: 'Turn Indicator, Side Repeater', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Lumen Automotive' },
    { id: 'TL-8621', name: 'Tail Lamp Assy', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Lumen Automotive' },
    { id: 'BP-8701', name: 'Front Bumper Fascia', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Stamping Co.' },
    { id: 'GR-8711', name: 'Grille Assy', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Midwest Stamping Co.' },
    { id: 'MR-8721', name: 'Exterior Mirror, Power Fold', uom: 'EA', type: 'Purchased', tracking: 'Lot', supplier: 'Clearview Glass' },
    { id: 'RD-8801', name: 'Front Radar Sensor (ADAS)', uom: 'EA', type: 'Purchased', tracking: 'Serial', pattern: '^RD\\d{8}$', supplier: 'Vantec Electronics' },
    { id: 'CL-9201', name: 'Coolant, OAT 50/50', uom: 'L', type: 'Purchased', tracking: 'Lot', supplier: 'Petrolux' },
    { id: 'BF-9202', name: 'Brake Fluid DOT 4', uom: 'L', type: 'Purchased', tracking: 'Lot', supplier: 'Petrolux' },
  ];

  /* BOM lines: op = routing operation where the component is consumed. slot distinguishes serialized positions. */
  const boms = {
    'BIW-T1': [
      { partId: 'UB-1001', qty: 1, op: 10 },
      { partId: 'SEA-9001', qty: 0.4, op: 20 },
      { partId: 'SF-2001L', qty: 1, op: 20 },
      { partId: 'SF-2001R', qty: 1, op: 20 },
      { partId: 'RF-3001', qty: 1, op: 30 },
      { partId: 'HD-3101', qty: 1, op: 30 },
      { partId: 'DR-3201', qty: 2, op: 30 },
      { partId: 'TG-3301', qty: 1, op: 30 },
      { partId: 'PNT-9002', qty: 3.2, op: 50 },
    ],
    'ENG-24T': [
      { partId: 'EB-4001', qty: 1, op: 10, slot: 'Block' },
      { partId: 'CK-4101', qty: 1, op: 20, slot: 'Crankshaft' },
      { partId: 'PS-4201', qty: 4, op: 20 },
      { partId: 'CR-4202', qty: 4, op: 20 },
      { partId: 'CH-4301', qty: 1, op: 30, slot: 'Cylinder Head' },
      { partId: 'CS-4302', qty: 2, op: 30 },
      { partId: 'GK-4601', qty: 1, op: 30 },
      { partId: 'TC-4401', qty: 1, op: 40, slot: 'Turbocharger' },
      { partId: 'EC-4501', qty: 1, op: 40, slot: 'ECM' },
      { partId: 'OL-9101', qty: 5.2, op: 50 },
    ],
    'VEH-T1': [
      { partId: 'BIW-T1', qty: 1, op: 10, slot: 'Body' },
      { partId: 'WH-7101', qty: 1, op: 20 },
      { partId: 'HL-8021', qty: 1, op: 30 },
      { partId: 'IP-8001', qty: 1, op: 40 },
      { partId: 'IC-8101', qty: 1, op: 50, slot: 'Instrument Cluster' },
      { partId: 'CN-8151', qty: 1, op: 60 },
      { partId: 'SH-8161', qty: 1, op: 60 },
      { partId: 'HU-8201', qty: 1, op: 70, slot: 'Head Unit' },
      { partId: 'SC-8301', qty: 1, op: 80, slot: 'Steering Column' },
      { partId: 'SW-8311', qty: 1, op: 80 },
      { partId: 'AB-6001', qty: 1, op: 80, slot: 'Driver Airbag' },
      { partId: 'ENG-24T', qty: 1, op: 90, slot: 'Engine' },
      { partId: 'TR-5001', qty: 1, op: 90, slot: 'Transmission' },
      { partId: 'RK-5301', qty: 1, op: 100 },
      { partId: 'AX-5101', qty: 1, op: 110, slot: 'Rear Axle' },
      { partId: 'FL-5401', qty: 1, op: 120 },
      { partId: 'EX-5501', qty: 1, op: 130 },
      { partId: 'WT-5201', qty: 4, op: 140 },
      { partId: 'WS-8501', qty: 1, op: 150 },
      { partId: 'UR-9301', qty: 0.6, op: 150 },
      { partId: 'DT-8551', qty: 2, op: 160 },
      { partId: 'SE-8401', qty: 1, op: 170, slot: 'Seat LH' },
      { partId: 'SE-8401', qty: 1, op: 170, slot: 'Seat RH' },
      { partId: 'RS-8451', qty: 1, op: 180 },
      { partId: 'AB-6002', qty: 1, op: 190, slot: 'Passenger Airbag' },
      { partId: 'SB-6101', qty: 1, op: 190, slot: 'Pretensioner LH' },
      { partId: 'SB-6101', qty: 1, op: 190, slot: 'Pretensioner RH' },
      { partId: 'LP-8601', qty: 2, op: 200 },
      { partId: 'TI-8611', qty: 2, op: 200 },
      { partId: 'TL-8621', qty: 2, op: 200 },
      { partId: 'BP-8701', qty: 1, op: 210 },
      { partId: 'GR-8711', qty: 1, op: 210 },
      { partId: 'MR-8721', qty: 2, op: 210 },
      { partId: 'RD-8801', qty: 1, op: 210, slot: 'Front Radar' },
      { partId: 'CL-9201', qty: 9.8, op: 220 },
      { partId: 'BF-9202', qty: 1.1, op: 220 },
      { partId: 'BT-7001', qty: 1, op: 230, slot: 'Battery' },
    ],
  };

  const routings = {
    'BIW-T1': [
      { seq: 10, name: 'Underbody Framing', station: 'B10-UB1', stdMin: 55, instr: ['Load UB-1001 on framing fixture F-UB-02; verify locator pins seat fully.', 'Run robot program UB_T1_P14 (148 spot welds).', 'Pull one weld coupon per shift for peel test.'] },
      { seq: 20, name: 'Side Frame Weld & Seal', station: 'B10-SF1', stdMin: 70, instr: ['Hang LH/RH side frames; confirm hand markings.', 'Apply 2K sealer bead along rocker flange before clamp.', 'Measure B-pillar gap with feeler gauge FG-12 on both sides.'] },
      { seq: 30, name: 'Roof & Closures Hang', station: 'B10-CL1', stdMin: 80, instr: ['Install roof panel and laser braze seams.', 'Hang hood, front doors and tailgate using hinge jigs HJ-3x.', 'Gauge hood gap and door flush with digital gap/flush gauge GF-7.'] },
      { seq: 40, name: 'Body Dimensional (CMM)', station: 'B10-CMM', stdMin: 45, instr: ['Load body on CMM fixture; run program BIW_T1_R07.', 'Record deviation for key control points UB-101, UB-102, RF-210.'] },
      { seq: 50, name: 'E-coat & Paint', station: 'B10-PNT', stdMin: 240, instr: ['E-coat dip, cure 180 °C × 20 min.', 'Apply topcoat Glacier White; measure film build with Elcometer DFT-3.'] },
      { seq: 60, name: 'Body Final Inspection', station: 'B10-BFI', stdMin: 30, instr: ['Inspect under L-light tunnel for paint defects.', 'Verify body serial label; release body to buffer.'] },
    ],
    'ENG-24T': [
      { seq: 10, name: 'Block Prep & Serialization', station: 'B20-BLK', stdMin: 25, instr: ['Scan block DMC; laser-etch engine serial on boss.', 'Install oil galley plugs; bore gauge cylinder #1.'] },
      { seq: 20, name: 'Crank & Piston Install', station: 'B20-CRK', stdMin: 45, instr: ['Install crankshaft; torque main caps 95 Nm (DC nutrunner NR-4).', 'Install pistons with arrow to front; measure end play with dial indicator DI-2.'] },
      { seq: 30, name: 'Head & Valvetrain', station: 'B20-HD', stdMin: 50, instr: ['Install head gasket and cylinder head; torque-angle head bolts.', 'Set valve lash; align timing marks.'] },
      { seq: 40, name: 'Turbo & ECM Dress', station: 'B20-DRS', stdMin: 35, instr: ['Mount turbocharger; torque oil feed banjo.', 'Mount ECM and flash calibration 24T-3.1.4.'] },
      { seq: 50, name: 'Cold Test', station: 'B20-CT', stdMin: 12, test: 'Engine Cold Test', equipment: 'CT-1 Motoring Stand', instr: ['Dock engine on CT-1; motor at 600 rpm.', 'Record per-cylinder compression and motored oil pressure.'] },
      { seq: 60, name: 'Hot Test & Release', station: 'B20-HT', stdMin: 20, test: 'Engine Hot Test', equipment: 'HT-2 Dynamometer', instr: ['Fire engine; run 8-minute hot test profile HT-24T-B.', 'Pressure-decay leak test coolant jacket; release to dispatch dock.'] },
    ],
    'VEH-T1': [
      { seq: 10, name: "Body Marriage & VIN", station: 'B30-TR1', stdMin: 14, instr: ["Call painted body from sequencing; scan body serial.", "Stamp VIN on frame rail and confirm check digit."] },
      { seq: 20, name: "Main Harness Routing", station: 'B30-TR2', stdMin: 12, instr: ["Route main harness along cowl and floor; seat all grommets.", "Torque ground studs G101\u2013G104."] },
      { seq: 30, name: "Headliner & Roof Trim", station: 'B30-TR3', stdMin: 10, instr: ["Install headliner through windshield opening; clip and connect dome lamps."] },
      { seq: 40, name: "Instrument Panel Install", station: 'B30-TR4', stdMin: 16, instr: ["Robot-load IP module with cross-car beam; torque beam-to-A-pillar bolts.", "Connect IP harness connectors C200\u2013C215."] },
      { seq: 50, name: "Instrument Cluster", station: 'B30-TR5', stdMin: 8, instr: ["Install and scan instrument cluster; run lamp/telltale self test."] },
      { seq: 60, name: "Center Console & Shifter", station: 'B30-TR6', stdMin: 12, instr: ["Install console and e-shifter; verify P-R-N-D detents on scan tool."] },
      { seq: 70, name: "Infotainment Head Unit", station: 'B30-TR7', stdMin: 9, instr: ["Install and scan head unit; confirm boot and camera feed."] },
      { seq: 80, name: "Steering Column & Wheel", station: 'B30-TR8', stdMin: 15, instr: ["Install EPS column; torque intermediate shaft pinch bolt.", "Install steering wheel and driver airbag; torque wheel nut; clockspring centered."] },
      { seq: 90, name: "Powertrain Decking", station: 'B30-DK', stdMin: 16, instr: ["Scan engine and transmission serials; deck powertrain on AGV carrier.", "Torque engine and transmission mounts."] },
      { seq: 100, name: "Front Suspension & Steering Rack", station: 'B30-CH1', stdMin: 14, instr: ["Install steering rack; torque tie-rod ends and stabilizer links."] },
      { seq: 110, name: "Rear Axle & Suspension", station: 'B30-CH2', stdMin: 14, instr: ["Install rear axle; torque U-bolts and shock mounts."] },
      { seq: 120, name: "Brake & Fuel Lines", station: 'B30-CH3', stdMin: 12, instr: ["Route and clip brake lines; connect fuel line quick-connects with audible click and pull test."] },
      { seq: 130, name: "Exhaust & Heat Shields", station: 'B30-CH4', stdMin: 10, instr: ["Hang exhaust system; torque manifold flange; install heat shields."] },
      { seq: 140, name: "Wheels & Tires", station: 'B30-CH5', stdMin: 10, instr: ["Mount wheels; torque lug nuts 190 N\u00b7m in star pattern with multi-spindle."] },
      { seq: 150, name: "Glass Install", station: 'B30-TG1', stdMin: 14, instr: ["Robot-apply urethane bead; set windshield with vision guidance."] },
      { seq: 160, name: "Doors & Door Trim", station: 'B30-TG2', stdMin: 16, instr: ["Re-hang doors from paint; set flush; install door trim panels."] },
      { seq: 170, name: "Front Seats", station: 'B30-TG3', stdMin: 12, instr: ["Scan and install LH/RH front seats; torque seat track bolts; connect occupant classification sensor."] },
      { seq: 180, name: "Rear Seat", station: 'B30-TG4', stdMin: 8, instr: ["Install rear bench; verify 60/40 latches."] },
      { seq: 190, name: "Restraints & SRS", station: 'B30-TG5', stdMin: 14, instr: ["Install passenger airbag and front pretensioners; scan each serial.", "Seat SRS connectors with CPA locks."] },
      { seq: 200, name: "Exterior Lighting & Indicators", station: 'B30-TG6', stdMin: 12, instr: ["Install headlamps, side repeaters and tail lamps.", "Function-check all indicators and hazard lamps."] },
      { seq: 210, name: "Bumpers, Grille & Mirrors", station: 'B30-TG7', stdMin: 14, instr: ["Install front fascia with radar sensor, grille and mirrors; gauge fascia gaps."] },
      { seq: 220, name: "Fluids Fill", station: 'B30-FL1', stdMin: 10, instr: ["Vacuum-fill coolant and brake fluid; verify no leaks at fill points."] },
      { seq: 230, name: "Battery & 12V Electrical", station: 'B30-FL2', stdMin: 8, instr: ["Install and scan battery; record open-circuit voltage."] },
      { seq: 240, name: "Module Flash & Configuration", station: 'B30-FL3', stdMin: 12, instr: ["Write VIN to all modules; flash calibration set T1-CAL-2027.3; clear DTCs."] },
      { seq: 250, name: "Alignment & Headlamp Aim", station: 'B30-EOL1', stdMin: 12, test: "Vehicle Alignment Test", equipment: "EOL Bay 1 \u2014 4-wheel Aligner", instr: ["Set front toe and camber; aim headlamps."] },
      { seq: 260, name: "Roll & Brake Test", station: 'B30-EOL2', stdMin: 10, test: "Vehicle Roll & Brake Test", equipment: "EOL Bay 2 \u2014 Roller Dyno + Brake Tester", instr: ["Roll test to 100 km/h; roller brake test; OBD scan."] },
      { seq: 270, name: "ADAS Calibration", station: 'B30-EOL3', stdMin: 10, test: "ADAS Calibration", equipment: "EOL Bay 3 \u2014 Target Frame", instr: ["Calibrate front radar and windshield camera against targets."] },
      { seq: 280, name: "Water Test", station: 'B30-WT', stdMin: 10, test: "Vehicle Water Test", equipment: "Monsoon Booth W-1", instr: ["Run 6-minute monsoon cycle; inspect cabin, bed and tail lamps."] },
      { seq: 290, name: "Final Audit & Ship Release", station: 'B30-AUD', stdMin: 10, instr: ["Final audit walk-around; release to ship yard."] },
    ],
  };

  /* ---- quality plan characteristic builders ---- */
  const chk = (name, o = {}) => ({ type: 'check', name, phase: o.phase || 'in', sev: o.sev || 'Minor', required: true, cat: o.cat || 'Workmanship' });
  const endchk = (name) => chk(name, { phase: 'end', cat: 'Workmanship' });
  const meas = (name, unit, nominal, lsl, usl, dec, o = {}) => ({ type: 'measure', name, unit, nominal, lsl, usl, dec, gauge: o.gauge || '', sev: o.sev || 'Minor', cat: o.cat || 'Dimensional', required: true, phase: 'in' });
  const calc = (name, formula, unit, lsl, usl, dec, o = {}) => ({ type: 'calc', name, formula, unit, lsl, usl, dec, sev: o.sev || 'Minor', cat: o.cat || 'Dimensional', required: true, phase: 'in' });
  const ser = (partId, slot, o = {}) => ({ type: 'serial', name: 'Scan ' + slot + ' serial', partId, slot, sev: o.sev || 'Major', cat: 'Traceability', required: true, phase: 'in' });
  const sign = (role, meaning, name) => ({ type: 'signoff', name: name || (role + ' sign-off'), role, meaning, required: true, phase: 'end', sev: 'Minor', cat: 'Documentation' });

  const planSteps = {
    'BIW-T1': {
      10: [
        chk('Underbody part number & revision match build sheet'),
        chk('Locator pins engaged and clamps closed before weld cycle'),
        meas('Weld count, underbody (robot counter)', 'welds', 148, 148, 148, 0, { cat: 'Weld', sev: 'Major' }),
        meas('Weld coupon nugget diameter', 'mm', 6.0, 5.0, 7.5, 1, { gauge: 'Caliper CAL-118', cat: 'Weld', sev: 'Major' }),
        endchk('Weld tips dressed; station 5S and FOD sweep complete'),
        sign('Operator', 'Performed'),
      ],
      20: [
        chk('LH/RH side frames correct hand (stamp mark visible)'),
        meas('B-pillar gap to underbody, LH', 'mm', 1.0, 0.5, 1.5, 2, { gauge: 'Feeler FG-12' }),
        meas('B-pillar gap to underbody, RH', 'mm', 1.0, 0.5, 1.5, 2, { gauge: 'Feeler FG-12' }),
        calc('Cross-car gap delta |LH − RH|', 'abs(C2 - C3)', 'mm', 0, 0.5, 2),
        meas('Sealer bead width, rocker flange', 'mm', 6.0, 4.0, 8.0, 1, { gauge: 'Bead gauge BG-3', cat: 'Sealing' }),
        endchk('Sealer nozzle purged & capped; spatter cleared from fixture'),
        sign('Operator', 'Performed'),
      ],
      30: [
        meas('Hood gap to fender, LH', 'mm', 4.0, 3.0, 5.0, 2, { gauge: 'Gap/Flush GF-7' }),
        meas('Hood gap to fender, RH', 'mm', 4.0, 3.0, 5.0, 2, { gauge: 'Gap/Flush GF-7' }),
        calc('Hood gap parallelism', 'abs(C1 - C2)', 'mm', 0, 0.6, 2),
        meas('Front door flush, LH', 'mm', 0.0, -0.5, 0.5, 2, { gauge: 'Gap/Flush GF-7' }),
        meas('Front door flush, RH', 'mm', 0.0, -0.5, 0.5, 2, { gauge: 'Gap/Flush GF-7' }),
        chk('Tailgate hinge bolts torque-striped'),
        endchk('Hinge jigs returned; closures dolly empty'),
        sign('Operator', 'Performed'),
      ],
      40: [
        chk('CMM program BIW_T1_R07 loaded and fixture verified'),
        meas('CMM pt UB-101 X deviation', 'mm', 0, -0.7, 0.7, 2, { gauge: 'CMM Zeiss-02', sev: 'Major' }),
        meas('CMM pt UB-102 Y deviation', 'mm', 0, -0.7, 0.7, 2, { gauge: 'CMM Zeiss-02', sev: 'Major' }),
        meas('CMM pt RF-210 Z deviation', 'mm', 0, -1.0, 1.0, 2, { gauge: 'CMM Zeiss-02', sev: 'Major' }),
        calc('Worst-case deviation', 'max(abs(C2), abs(C3), abs(C4))', 'mm', 0, 1.0, 2, { sev: 'Major' }),
        sign('Quality Technician', 'Verified', 'Dimensional verification'),
      ],
      50: [
        chk('E-coat cure chart within 175–185 °C window'),
        meas('Paint film build, hood', 'µm', 135, 110, 160, 0, { gauge: 'Elcometer DFT-3', cat: 'Paint' }),
        meas('Paint film build, roof', 'µm', 135, 110, 160, 0, { gauge: 'Elcometer DFT-3', cat: 'Paint' }),
        sign('Operator', 'Performed'),
      ],
      60: [
        chk('No weld spatter, burrs or sharp edges in door openings'),
        chk('L-light paint audit: no craters, runs, dirt > 0.5 mm', { cat: 'Paint' }),
        chk('Body serial label applied and legible'),
        sign('Quality Technician', 'Verified', 'Body release'),
      ],
    },
    'ENG-24T': {
      10: [
        ser('EB-4001', 'Block'),
        chk('Oil galley plugs installed and paint-marked', { sev: 'Major' }),
        meas('Cylinder #1 bore diameter', 'mm', 88.000, 87.990, 88.010, 3, { gauge: 'Bore gauge BG-88' }),
        sign('Operator', 'Performed'),
      ],
      20: [
        ser('CK-4101', 'Crankshaft'),
        meas('Main cap bolt final torque (avg)', 'N·m', 95, 90, 100, 1, { gauge: 'Nutrunner NR-4', cat: 'Torque', sev: 'Major' }),
        meas('Crankshaft end play', 'mm', 0.18, 0.08, 0.30, 2, { gauge: 'Dial ind. DI-2' }),
        meas('Crank rotating torque', 'N·m', 12, 5, 20, 1, { gauge: 'Torque wrench TW-9', cat: 'Torque' }),
        chk('Piston arrows toward timing end', { sev: 'Major' }),
        endchk('Nutrunner counts reconciled; no loose fasteners in tray'),
        sign('Operator', 'Performed'),
      ],
      30: [
        ser('CH-4301', 'Cylinder Head'),
        meas('Head bolt final angle', '°', 90, 85, 95, 0, { gauge: 'Nutrunner NR-6', cat: 'Torque', sev: 'Major' }),
        meas('Valve lash, intake', 'mm', 0.20, 0.17, 0.23, 2, { gauge: 'Feeler FG-4' }),
        meas('Valve lash, exhaust', 'mm', 0.28, 0.25, 0.31, 2, { gauge: 'Feeler FG-4' }),
        chk('Cam timing marks aligned; chain tensioner pin pulled', { sev: 'Major' }),
        sign('Operator', 'Performed'),
      ],
      40: [
        ser('TC-4401', 'Turbocharger'),
        ser('EC-4501', 'ECM'),
        meas('Turbo oil feed banjo torque', 'N·m', 30, 27, 33, 1, { gauge: 'Torque wrench TW-3', cat: 'Torque' }),
        chk('ECM flashed to calibration 24T-3.1.4 (checksum OK)', { cat: 'Electrical', sev: 'Major' }),
        endchk('Protective caps on turbo inlet/outlet; FOD check'),
        sign('Operator', 'Performed'),
      ],
      50: [
        meas('Compression, cylinder 1', 'kPa', 1350, 1200, 1500, 0, { cat: 'Test', sev: 'Major' }),
        meas('Compression, cylinder 2', 'kPa', 1350, 1200, 1500, 0, { cat: 'Test', sev: 'Major' }),
        meas('Compression, cylinder 3', 'kPa', 1350, 1200, 1500, 0, { cat: 'Test', sev: 'Major' }),
        meas('Compression, cylinder 4', 'kPa', 1350, 1200, 1500, 0, { cat: 'Test', sev: 'Major' }),
        calc('Compression spread (max−min)/max', '(max(C1,C2,C3,C4) - min(C1,C2,C3,C4)) / max(C1,C2,C3,C4) * 100', '%', 0, 10, 1, { cat: 'Test', sev: 'Major' }),
        meas('Motored oil pressure @ 600 rpm', 'kPa', 180, 120, 300, 0, { cat: 'Test' }),
        sign('Quality Technician', 'Verified', 'Cold test verification'),
      ],
      60: [
        meas('Hot oil pressure @ idle', 'kPa', 150, 100, 250, 0, { cat: 'Test' }),
        meas('Idle speed, stabilized', 'rpm', 750, 700, 800, 0, { cat: 'Test' }),
        meas('Coolant jacket pressure decay', 'Pa/min', 10, 0, 40, 0, { cat: 'Leak', sev: 'Major' }),
        chk('No visible oil or coolant leaks after hot run', { cat: 'Leak', sev: 'Major' }),
        sign('Quality Engineer', 'Approved', 'Engine release'),
      ],
    },
    'VEH-T1': {
      10: [
        ser('BIW-T1', 'Body'),
        chk('VIN stamp legible and matches build sheet (check digit valid)', { sev: 'Major', cat: 'Traceability' }),
        sign('Operator', 'Performed'),
      ],
      20: [
        chk('Main harness routed; all grommets seated', { cat: 'Electrical' }),
        meas('Ground stud G101 torque', 'N·m', 12, 10, 14, 1, { gauge: 'Torque driver TD-5', cat: 'Torque' }),
        sign('Operator', 'Performed'),
      ],
      30: [
        chk('Headliner clips engaged; dome lamp connectors seated'),
        sign('Operator', 'Performed'),
      ],
      40: [
        meas('Cross-car beam bolt torque, LH', 'N·m', 45, 40, 50, 1, { gauge: 'Nutrunner NR-21', cat: 'Torque', sev: 'Major' }),
        meas('Cross-car beam bolt torque, RH', 'N·m', 45, 40, 50, 1, { gauge: 'Nutrunner NR-21', cat: 'Torque', sev: 'Major' }),
        chk('IP connectors C200–C215 seated with CPA', { cat: 'Electrical' }),
        endchk('Loose clips and wrapping removed from cabin'),
        sign('Operator', 'Performed'),
      ],
      50: [
        ser('IC-8101', 'Instrument Cluster'),
        chk('Cluster telltale self-test: all lamps illuminate', { cat: 'Electrical' }),
        sign('Operator', 'Performed'),
      ],
      60: [
        chk('Console latches and armrest hinge function'),
        chk('E-shifter P-R-N-D positions read correctly on scan tool', { sev: 'Major', cat: 'Electrical' }),
        sign('Operator', 'Performed'),
      ],
      70: [
        ser('HU-8201', 'Head Unit'),
        chk('Head unit boots; rear camera feed displayed', { cat: 'Electrical' }),
        sign('Operator', 'Performed'),
      ],
      80: [
        ser('SC-8301', 'Steering Column', { sev: 'Critical' }),
        ser('AB-6001', 'Driver Airbag', { sev: 'Critical' }),
        meas('Intermediate shaft pinch bolt torque', 'N·m', 35, 32, 38, 1, { gauge: 'Nutrunner NR-23', cat: 'Torque', sev: 'Critical' }),
        meas('Steering wheel nut torque', 'N·m', 50, 45, 55, 1, { gauge: 'Nutrunner NR-24', cat: 'Torque', sev: 'Critical' }),
        meas('Driver airbag module bolt torque', 'N·m', 9.0, 7.5, 10.5, 1, { gauge: 'Torque driver TD-2', cat: 'Torque', sev: 'Critical' }),
        chk('Clockspring centered; horn and wheel switches function', { sev: 'Major', cat: 'Electrical' }),
        sign('Operator', 'Performed'),
        sign('Quality Technician', 'Verified', 'Safety-critical steering verification'),
      ],
      90: [
        ser('ENG-24T', 'Engine'),
        ser('TR-5001', 'Transmission'),
        meas('Engine mount bolt torque, LH', 'N·m', 110, 100, 120, 1, { gauge: 'Nutrunner NR-11', cat: 'Torque', sev: 'Major' }),
        meas('Engine mount bolt torque, RH', 'N·m', 110, 100, 120, 1, { gauge: 'Nutrunner NR-11', cat: 'Torque', sev: 'Major' }),
        meas('Transmission mount torque', 'N·m', 85, 75, 95, 1, { gauge: 'Nutrunner NR-12', cat: 'Torque', sev: 'Major' }),
        endchk('AGV carrier returned; no loose hardware on floor'),
        sign('Operator', 'Performed'),
      ],
      100: [
        meas('Tie-rod end nut torque, LH', 'N·m', 80, 72, 88, 1, { gauge: 'Nutrunner NR-31', cat: 'Torque', sev: 'Critical' }),
        meas('Tie-rod end nut torque, RH', 'N·m', 80, 72, 88, 1, { gauge: 'Nutrunner NR-31', cat: 'Torque', sev: 'Critical' }),
        chk('Cotter pins installed and bent', { sev: 'Critical' }),
        sign('Operator', 'Performed'),
      ],
      110: [
        ser('AX-5101', 'Rear Axle'),
        meas('Axle U-bolt torque (avg)', 'N·m', 140, 130, 150, 0, { gauge: 'Nutrunner NR-33', cat: 'Torque', sev: 'Major' }),
        sign('Operator', 'Performed'),
      ],
      120: [
        chk('Brake lines clipped at all 9 clip points', { sev: 'Major' }),
        chk('Fuel quick-connects: audible click and pull test', { sev: 'Critical', cat: 'Leak' }),
        sign('Operator', 'Performed'),
      ],
      130: [
        meas('Exhaust manifold flange torque', 'N·m', 40, 36, 44, 1, { gauge: 'Nutrunner NR-35', cat: 'Torque' }),
        chk('Heat shields clear of fuel and brake lines (min 25 mm)'),
        sign('Operator', 'Performed'),
      ],
      140: [
        meas('Wheel nut torque, LF', 'N·m', 190, 175, 205, 0, { gauge: 'Multi-spindle WN-2', cat: 'Torque', sev: 'Major' }),
        meas('Wheel nut torque, RF', 'N·m', 190, 175, 205, 0, { gauge: 'Multi-spindle WN-2', cat: 'Torque', sev: 'Major' }),
        meas('Wheel nut torque, LR', 'N·m', 190, 175, 205, 0, { gauge: 'Multi-spindle WN-2', cat: 'Torque', sev: 'Major' }),
        meas('Wheel nut torque, RR', 'N·m', 190, 175, 205, 0, { gauge: 'Multi-spindle WN-2', cat: 'Torque', sev: 'Major' }),
        calc('Wheel nut torque spread', 'max(C1,C2,C3,C4) - min(C1,C2,C3,C4)', 'N·m', 0, 20, 0, { cat: 'Torque' }),
        sign('Operator', 'Performed'),
      ],
      150: [
        meas('Urethane bead height', 'mm', 12, 10, 14, 1, { gauge: 'Vision VS-3', cat: 'Sealing' }),
        chk('Windshield camera bracket bonded and seated', { sev: 'Major' }),
        sign('Operator', 'Performed'),
      ],
      160: [
        meas('Front door flush to fender, LH', 'mm', 0.0, -0.7, 0.7, 2, { gauge: 'Gap/Flush GF-7' }),
        meas('Front door flush to fender, RH', 'mm', 0.0, -0.7, 0.7, 2, { gauge: 'Gap/Flush GF-7' }),
        chk('Door trim panels clipped; window switches function'),
        sign('Operator', 'Performed'),
      ],
      170: [
        ser('SE-8401', 'Seat LH', { sev: 'Critical' }),
        ser('SE-8401', 'Seat RH', { sev: 'Critical' }),
        meas('Seat track bolt torque (avg)', 'N·m', 50, 45, 55, 1, { gauge: 'Nutrunner NR-41', cat: 'Torque', sev: 'Critical' }),
        chk('Occupant classification sensor connected; no SRS DTC', { sev: 'Critical', cat: 'Electrical' }),
        sign('Operator', 'Performed'),
      ],
      180: [
        chk('Rear bench 60/40 latches engage; child-seat anchors accessible', { sev: 'Major' }),
        sign('Operator', 'Performed'),
      ],
      190: [
        ser('AB-6002', 'Passenger Airbag', { sev: 'Critical' }),
        ser('SB-6101', 'Pretensioner LH', { sev: 'Critical' }),
        ser('SB-6101', 'Pretensioner RH', { sev: 'Critical' }),
        chk('SRS connectors seated, CPA locks engaged', { sev: 'Critical', cat: 'Electrical' }),
        endchk('Trim clips and fasteners reconciled; no stray parts in cabin'),
        sign('Operator', 'Performed'),
        sign('Quality Technician', 'Verified', 'Safety-critical restraint verification'),
      ],
      200: [
        chk('Headlamps low/high beam function', { cat: 'Electrical' }),
        chk('Turn indicators and side repeaters flash LH/RH; hazard function', { sev: 'Major', cat: 'Electrical' }),
        meas('Turn indicator flash rate', 'flashes/min', 90, 60, 120, 0, { gauge: 'Lamp tester LT-1', cat: 'Electrical', sev: 'Major' }),
        chk('Tail, stop and reverse lamps function', { sev: 'Major', cat: 'Electrical' }),
        sign('Operator', 'Performed'),
      ],
      210: [
        ser('RD-8801', 'Front Radar', { sev: 'Major' }),
        meas('Fascia-to-hood gap', 'mm', 4.0, 3.0, 5.0, 1, { gauge: 'Gap/Flush GF-7' }),
        chk('Mirrors power-fold and adjust'),
        sign('Operator', 'Performed'),
      ],
      220: [
        meas('Coolant fill volume', 'L', 9.8, 9.5, 10.2, 2, { gauge: 'Fill rig FR-1', cat: 'Fluids' }),
        meas('Brake fluid fill volume', 'L', 1.10, 1.00, 1.25, 2, { gauge: 'Fill rig FR-2', cat: 'Fluids' }),
        sign('Operator', 'Performed'),
      ],
      230: [
        ser('BT-7001', 'Battery'),
        meas('Battery open-circuit voltage', 'V', 12.65, 12.40, 12.90, 2, { gauge: 'DMM Fluke-87', cat: 'Electrical' }),
        sign('Operator', 'Performed'),
      ],
      240: [
        chk('VIN written to all 38 modules; calibration T1-CAL-2027.3 verified', { sev: 'Major', cat: 'Electrical' }),
        chk('DTCs cleared after configuration', { cat: 'Electrical' }),
        sign('Operator', 'Performed'),
      ],
      250: [
        meas('Front toe, LH', '°', 0.10, 0.00, 0.20, 2, { cat: 'Test' }),
        meas('Front toe, RH', '°', 0.10, 0.00, 0.20, 2, { cat: 'Test' }),
        calc('Total front toe', 'C1 + C2', '°', 0.05, 0.35, 2, { cat: 'Test' }),
        meas('Headlamp aim, low beam vertical', '%', -1.0, -1.5, -0.5, 2, { cat: 'Test' }),
        sign('Quality Technician', 'Verified', 'Alignment verification'),
      ],
      260: [
        meas('Brake force, front LH', 'kN', 3.8, 3.0, 4.6, 2, { cat: 'Test', sev: 'Major' }),
        meas('Brake force, front RH', 'kN', 3.8, 3.0, 4.6, 2, { cat: 'Test', sev: 'Major' }),
        calc('Front brake imbalance', 'abs(C1 - C2) / max(C1, C2) * 100', '%', 0, 20, 1, { cat: 'Test', sev: 'Major' }),
        chk('OBD scan: no stored or pending DTCs', { cat: 'Electrical', sev: 'Major' }),
        sign('Quality Technician', 'Verified', 'Roll & brake verification'),
      ],
      270: [
        meas('Front radar vertical alignment', '°', 0.0, -0.5, 0.5, 2, { cat: 'Test', sev: 'Major' }),
        meas('Front radar horizontal alignment', '°', 0.0, -0.5, 0.5, 2, { cat: 'Test', sev: 'Major' }),
        chk('Windshield camera calibration complete', { cat: 'Test', sev: 'Major' }),
        sign('Quality Technician', 'Verified', 'ADAS calibration verification'),
      ],
      280: [
        meas('Monsoon cycle duration', 'min', 6, 6, 8, 0, { cat: 'Leak' }),
        chk('No water ingress — cabin floor, A-pillars, headliner', { cat: 'Leak', sev: 'Major' }),
        chk('No water ingress — tail lamps and bed junction box', { cat: 'Leak' }),
        sign('Quality Technician', 'Verified', 'Water test verification'),
      ],
      290: [
        chk('Final audit: paint, fit & finish, labels'),
        chk('Owner manual, keys (2) and tire inflator present'),
        sign('Quality Engineer', 'Approved', 'Vehicle release to ship'),
      ],
    },
  };

  return { company, buildings, locations, stations, people, parts, boms, routings, planSteps, builders: { chk, endchk, meas, calc, ser, sign } };
})();
